#!/bin/bash

# The script adds a symbol into force-dynamic file
# adding boilerplate text and increasing the counter
#
# Usage: ./add_deps /path/to/file symbol1 symbol2 symbol3

FILE=$1
OLD_AMOUNT=$(sed -n 5p $FILE)
NEW_AMOUNT=$(($OLD_AMOUNT - 1 + $#))

shift

sed -i '5s/'$OLD_AMOUNT'/'$NEW_AMOUNT'/g' $FILE

for i in ${1+"$@"}; do
  echo "Ud -1	$i
	1 0" >> $FILE
done
