#!/bin/bash

# Path pattern of obs hosts store auxiliary information between runs
HOST_DIR="*obs*"
# Path pattern of deps files with forced symbols
FORCE_FILES="force/*"
# Patterns for auxiliary files
JF_FILES="jfunc-*"
DEPS_FILES="deps-*"
DLSYM_FILES="dlsym-*"

for i in "$@"; do
  case $i in
    --jfunc)
      JFUNC_FLAG=YES
      shift
      ;;
    --merge)
      MERGE_FLAG=YES
      shift
      ;;
    --plugin-hidden)
      PLUG_HID_FLAG=YES
      shift
      ;;
    --plugin-full)
      PLUG_FULL_FLAG=YES
      shift
      ;;
    --clean-aux)
      CLEAN_AUX_FLAG=YES
      shift
      ;;
    --clean-utils)
      CLEAN_UTILS_FLAG=YES
      shift
      ;;
    --clean-force)
      CLEAN_FORCE_FLAG=YES
      shift
      ;;
    --clean-r0)
      CLEAN_R0_FLAG=YES
      shift
      ;;
    --clean-r1)
      CLEAN_R1_FLAG=YES
      shift
      ;;
    *)
      UNKNOWN=YES
      ;;
  esac
done

if [ ! -z ${UNKNOWN+x} ]; then
  echo "Unknown option. Abort"
  exit 1
fi

# Do stuff with jump-functions
if [ ! -z ${JFUNC_FLAG+x} ]; then
  echo "===Started with jfuncs==="

  echo "Concatenating jfunc files"
  cat $HOST_DIR/$JF_FILES > jfunc_all

  echo "Transforming jfuncs to dlsym signatures"
  utils/jf2sign jfunc_all utils/dlsym-signs-base.txt > dlsym-signs.txt
  echo "===Done with jfuncs==="
fi

# Do stuff with merging deps-files
if [ ! -z ${MERGE_FLAG+x} ]; then
  echo "===Started with merging==="

  echo "Concatenating dlsym files"
  cat $HOST_DIR/$DLSYM_FILES > dlsym_all

  echo "Merging deps and dlsym files"
  utils/merge dlsym_all $(ls $FORCE_FILES) $(ls $HOST_DIR/$DEPS_FILES) > merged.vis
  echo "===Done with merging==="

  echo "===Started with merging for gcc plugin==="
  if [ ! -z ${PLUG_FULL_FLAG+x} ]; then
    echo "Full plugin amending"
    RES=$(utils/amend-merge-output.sh merged.vis)
    mv $RES merged.vis.gcc
  elif [ ! -z ${PLUG_HID_FLAG+x} ]; then
    echo "Hidden only plugin amending"
    RES=$(utils/amend-merge-output1.sh merged.vis)
    mv $RES merged.vis.gcc
  else
    echo "Ignore plugin"
    echo "0 0 0" > merged.vis.gcc
  fi
  echo "===Done with merging for gcc plugin==="
fi


if [ ! -z ${CLEAN_AUX_FLAG+x} ]; then
  rm -f merged*
  rm -f jfunc*
  rm -f dlsym*
fi

if [ ! -z ${CLEAN_UTILS_FLAG+x} ]; then
  rm -f utils/*
fi

if [ ! -z ${CLEAN_FORCE_FLAG+x} ]; then
  rm -f $FORCE_FILES
fi

if [ ! -z ${CLEAN_R0_FLAG+x} ]; then
  rm -f $HOST_DIR/$JF_FILES
fi

if [ ! -z ${CLEAN_R1_FLAG+x} ]; then
  rm -f $HOST_DIR/$DLSYM_FILES $HOST_DIR/$DEPS_FILES
fi

